import type { BuildCandidateSessionControllerResultArgs } from './useCandidateSessionControllerResult.types';

export function buildCandidateSessionControllerResult({
  finalView,
  state,
  authMessage,
  errorMessage,
  errorStatus,
  loginHref,
  derived,
  actions,
  candidateSessionId,
  schedule,
  detectedTimezone,
  timezoneOptions,
  windowState,
  codingWorkspace,
  lastDraftSavedAt,
  lastSubmissionAt,
  lastSubmissionId,
  onStart,
  onDashboard,
  onReview,
  onGoHome,
  token,
  onTaskWindowClosed,
  onCodingWorkspaceSnapshot,
}: BuildCandidateSessionControllerResultArgs) {
  const started = state.started || state.bootstrap?.status === 'in_progress';

  return {
    view: finalView,
    authStatus: state.authStatus,
    authMessage,
    errorMessage,
    errorStatus,
    loginHref,
    ...derived,
    started,
    submitting: actions.submitting,
    taskError: state.taskState.error,
    candidateSessionId,
    taskLoading: state.taskState.loading,
    scheduleDate: schedule.scheduleDate,
    scheduleTimezone: schedule.scheduleTimezone,
    scheduleGithubUsername: schedule.scheduleGithubUsername,
    scheduleTimezoneDetected: detectedTimezone,
    scheduleTimezoneOptions: timezoneOptions,
    scheduleDateError: schedule.scheduleDateError,
    scheduleTimezoneError: schedule.scheduleTimezoneError,
    scheduleGithubUsernameError: schedule.scheduleGithubUsernameError,
    scheduleSubmitError: schedule.scheduleSubmitError,
    schedulePreviewWindows: schedule.schedulePreviewWindows,
    scheduleResponseWindows: schedule.scheduleResponseWindows,
    scheduleCurrentDayWindow: schedule.scheduleCurrentDayWindow,
    scheduleCountdownLabel: schedule.scheduleCountdownLabel,
    scheduleCountdownTargetAt: schedule.scheduleCountdownTargetAt,
    scheduleDisplayTimezone: schedule.scheduleDisplayTimezone,
    scheduleDisplayStartAt: schedule.scheduleDisplayStartAt,
    windowState,
    actionGate: windowState.actionGate,
    codingWorkspace,
    lastDraftSavedAt,
    lastSubmissionAt,
    lastSubmissionId,
    onStart,
    onDashboard,
    onReview,
    onRetryInit: () => actions.runInit(token, true),
    onGoHome,
    onRetryTask: () => actions.fetchCurrentTask(undefined, { skipCache: true }),
    onScheduleDateChange: schedule.onScheduleDateChange,
    onScheduleTimezoneChange: schedule.onScheduleTimezoneChange,
    onScheduleGithubUsernameChange: schedule.onScheduleGithubUsernameChange,
    onScheduleContinue: schedule.onScheduleContinue,
    onScheduleBack: schedule.onScheduleBack,
    onScheduleConfirm: () => {
      void schedule.onScheduleConfirm();
    },
    onScheduleRetry: schedule.onScheduleRetry,
    onRefreshScheduleLock: schedule.onRefreshScheduleLock,
    onSubmit: actions.handleSubmit,
    onStartTests: actions.handleStartTests,
    onPollTests: actions.handlePollTests,
    onTaskWindowClosed,
    onCodingWorkspaceSnapshot,
  };
}
