import type { CandidateSession } from '@/features/recruiter/types';
import type { RowState } from '../hooks/types';
import type { SimulationPlan } from '../utils/plan';

export type SearchState = {
  search: string;
  setSearch: (value: string) => void;
  pagedCandidates: CandidateSession[];
  visibleCandidates: CandidateSession[];
  page: number;
  pageCount: number;
  setPage: (page: number) => void;
};

export type SimulationDetailViewProps = {
  simulationId: string;
  simulationStatus: string | null;
  scenarioVersionLabel: string;
  scenarioIdLabel: string | null;
  scenarioLocked: boolean;
  scenarioLockedAt: string | null;
  inviteEnabled: boolean;
  inviteDisabledReason: string | null;
  inviteResendEnabled: boolean;
  inviteResendDisabledReason: string | null;
  actionError: string | null;
  canApprove: boolean;
  approveLoading: boolean;
  onApprove: () => void;
  regenerateLoading: boolean;
  onRegenerate: () => void;
  terminatePending: boolean;
  terminateModalOpen: boolean;
  setTerminateModalOpen: (open: boolean) => void;
  onTerminate: () => Promise<void>;
  cleanupJobIds: string[];
  retryGenerateLoading: boolean;
  onRetryGenerate: () => void;
  templateKeyLabel: string;
  titleLabel: string;
  roleLabel: string;
  stackLabel: string;
  levelLabel: string;
  focusLabel: string;
  companyContextLabel: string;
  scenarioLabel: string | null;
  rubricSummary: string | null;
  planDays: { dayIndex: number; task: SimulationPlan['days'][number] | null }[];
  planLoading: boolean;
  planStatusCode: number | null;
  generating: boolean;
  jobFailureMessage: string | null;
  jobFailureCode: string | null;
  planError: string | null;
  reloadPlan: () => void;
  candidates: CandidateSession[];
  candidatesLoading: boolean;
  candidatesError: string | null;
  reloadCandidates: () => void;
  search: SearchState;
  rowStates: Record<string, RowState>;
  onCopy: (candidate: CandidateSession) => void;
  onResend: (candidate: CandidateSession) => void;
  onCloseManual: (id: string) => void;
  cooldownNow: number;
  inviteModalOpen: boolean;
  setInviteModalOpen: (open: boolean) => void;
  inviteFlowState: { status: string; message?: string | null };
  submitInvite: (name: string, email: string) => Promise<void>;
  resetInviteFlow: () => void;
};
